import React from 'react';

const PrivacyPolicy = () => {
  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 py-12 text-gray-800">
      <h1 className="text-3xl sm:text-4xl font-bold mb-8 text-center">Privacy Policy</h1>

      <div className="space-y-6 text-base sm:text-lg leading-relaxed">
        <p>Thank you for using Accord AI. We care deeply about your privacy and are committed to handling your data responsibly.</p>
        <p>This Privacy Policy explains how we collect, use, and protect your personal information when you use our services, including our AI models, platform interfaces, and associated websites and applications (collectively, the “Services”). By using our Services, you agree to the practices described below.</p>
        <p>If you have questions or concerns, you can always contact us at <a href="mailto:privacy@[yourdomain.com]" className="text-blue-600 hover:underline">privacy@[yourdomain.com]</a>.</p>

        <div>
          <h2 className="font-semibold text-xl mb-2">1. Information We Collect</h2>
          <p>When you create an account with Accord AI, we collect basic account information such as your name, email address, and, if applicable, your phone number and company name. Payment-related details are securely processed through third-party services like Cashfree or Stripe; we do not store your full payment credentials.</p>
          <p>We also collect information automatically when you use our platform. This includes technical data such as your IP address, browser type, device information, and usage activity — for example, the pages you visit, the features you interact with, and error logs that help us identify and resolve performance issues.</p>
          <p>In addition, when you interact with our AI, we collect the content you provide. This includes the text or data you enter into the platform (referred to as “Input”) and the AI-generated responses you receive (“Output”). Together, these are referred to as “Content.”</p>
        </div>

        <div>
          <h2 className="font-semibold text-xl mb-2">2. How We Use Your Information</h2>
          <p>We use your information primarily to operate, maintain, and improve the Accord AI platform. This includes authenticating your identity, processing payments, personalizing your experience, and providing customer support. We also use collected data to improve the overall safety, functionality, and performance of our Services.</p>
          <p>Most importantly, we may use your Input and Output to help train and refine our AI models. This helps us improve the accuracy, quality, and relevance of the responses generated by our systems. This training process is essential for delivering a better product over time.</p>
        </div>

        <div>
          <h2 className="font-semibold text-xl mb-2">3. Use of Data for AI Model Training</h2>
          <p>We want to be transparent: by default, your Input and Output may be used to train our AI models. This means that the conversations and interactions you have with Accord AI may be reviewed by our systems or teams to fine-tune our responses, enhance safety features, and identify areas for improvement. We take steps to de-identify such data where possible and do not use personal information like your name, contact details, or payment data in the model training process.</p>
          <p>If you do not want your data to be used for training purposes, you may opt out by contacting us at <a href="mailto:privacy@[yourdomain.com]" className="text-blue-600 hover:underline">privacy@[yourdomain.com]</a>. Please note that opting out may affect the personalization and performance of some AI features.</p>
        </div>

        <div>
          <h2 className="font-semibold text-xl mb-2">4. Data Sharing</h2>
          <p>We do not sell your personal information. We may share data with trusted service providers who support our operations, such as payment gateways, hosting providers, and analytics platforms. These third parties are required to adhere to strict confidentiality agreements and data protection practices.</p>
          <p>We may also share your information with legal authorities or regulatory bodies if required to comply with legal obligations or to protect our rights and users. Additionally, if you enable any third-party integrations, your data may be shared as necessary to complete those actions, governed by the respective third party’s terms and policies.</p>
        </div>

        <div>
          <h2 className="font-semibold text-xl mb-2">5. Data Retention</h2>
          <p>We retain your account and usage information as long as your account remains active or as needed to provide the Services. If you request account deletion, we will remove your personal data unless we are required by law or for legitimate business purposes (such as fraud prevention or regulatory compliance) to retain certain records. Content used for model improvement may be retained and stored in anonymized form.</p>
        </div>

        <div>
          <h2 className="font-semibold text-xl mb-2">6. Data Security</h2>
          <p>We implement industry-standard security measures to protect your information. This includes encryption of data in transit and at rest, access controls, monitoring, and regular security reviews. However, no method of online transmission or storage is 100% secure. We recommend that you protect your account with a strong password and notify us immediately of any suspected unauthorized use.</p>
        </div>

        <div>
          <h2 className="font-semibold text-xl mb-2">7. Your Rights and Choices</h2>
          <p>Depending on your jurisdiction, you may have legal rights regarding your data, including the right to access, correct, delete, or restrict the use of your personal information. You may also have the right to object to processing or to withdraw your consent. To exercise any of these rights, please contact us at <a href="mailto:privacy@[yourdomain.com]" className="text-blue-600 hover:underline">privacy@[yourdomain.com]</a>.</p>
        </div>

        <div>
          <h2 className="font-semibold text-xl mb-2">8. International Data Transfers</h2>
          <p>Our platform may operate on servers located in different countries. As a result, your data may be transferred to and stored in jurisdictions outside your own. In such cases, we ensure that adequate safeguards are in place in compliance with applicable data protection laws.</p>
        </div>

        <div>
          <h2 className="font-semibold text-xl mb-2">9. Children’s Privacy</h2>
          <p>Our Services are not intended for use by individuals under the age of 13 (or the minimum legal age required in your country). We do not knowingly collect personal information from children. If we become aware that we have inadvertently collected data from a child, we will take steps to delete it as soon as possible.</p>
        </div>

        <div>
          <h2 className="font-semibold text-xl mb-2">10. Changes to This Policy</h2>
          <p>We may update this Privacy Policy from time to time to reflect changes in legal requirements, technology, or our business practices. If we make material changes, we will notify you in advance through email or in-app notifications. Your continued use of the Services after any updates indicates your acceptance of the revised Policy.</p>
        </div>

        <div>
          <h2 className="font-semibold text-xl mb-2">11. Contact Us</h2>
          <p>If you have questions about this Privacy Policy, or if you wish to make a privacy-related request, you can contact us at:</p>
          <ul className="list-disc list-inside ml-4 space-y-1">
            <li>Email: <a href="mailto:privacy@[yourdomain.com]" className="text-blue-600 hover:underline">privacy@[yourdomain.com]</a></li>
            <li>Phone: [+91-XXXXXXXXXX]</li>
            <li>Address: [Your Registered Company Address]</li>
            <li>Data Protection Officer (if applicable): [Full Name]</li>
          </ul>
        </div>
      </div>
    </div>
  );
};

export default PrivacyPolicy;
